Bakery/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bakery.Models;

namespace Bakery.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            BakeryEntities db = new BakeryEntities();

            return View(db.Products.ToList());
        }
    }
}

Bakery/Controllers/SaleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bakery.Models;

namespace Bakery.Controllers
{
    public class SaleController : Controller
    {
        BakeryEntities db = new BakeryEntities();
        public SaleController()
        {

        
            IEnumerable<SelectListItem> cusLiItem = from s in db.People
                                                select new SelectListItem
                                                {
                                                    Text = s.PersonFirstName + " " + s.PersonLastName,
                                                    Value = s.PersonKey.ToString()
                                                };
            ViewBag.Customers = cusLiItem;

            IEnumerable<SelectListItem> empLiItem = from s in db.Employees
                                                    select new SelectListItem
                                                    {
                                                        Text = s.Person.PersonFirstName + " " + s.Person.PersonLastName,
                                                        Value = s.EmployeeKey.ToString()
                                                    };
            ViewBag.Employees = empLiItem;

            IEnumerable<SelectListItem> prodLiItem = from s in db.Products
                                                     select new SelectListItem
                                                     {
                                                         Text = s.ProductName,
                                                         Value = s.ProductKey.ToString()
                                                     };
            ViewBag.Products = prodLiItem;
        }
        // GET: Sale
        public ActionResult Index()
        {
            
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include = "SaleKey")]string sk)

        {
            var resultMessage = new Message();
            Sale sl;
            if (Request["SaleKey"] == "")
            {
                sl = new Sale();
                sl.SaleDate = DateTime.Now;
                db.Sales.Add(sl);
                
            }
            else
            {
                sl = db.Sales.Find(Int32.Parse(Request["SaleKey"]));
            }
            
            if (ModelState.IsValid)
            {
                
                var slDet = new SaleDetail();
                sl.CustomerKey = Int32.Parse(Request["CustomerKey"]);
                sl.EmployeeKey = Int32.Parse(Request["EmployeeKey"]);
                slDet.ProductKey = Int32.Parse(Request["Products"]);
                slDet.SaleDetailPriceCharged = db.Products.Find(Int32.Parse(Request["Products"])).ProductPrice;
                slDet.SaleDetailQuantity = Request["Quantity"] == "" ? 0 : Int32.Parse(Request["Quantity"]);
                slDet.SaleDetailDiscount = Request["Discount"] == "" ? 0 : Int32.Parse(Request["Discount"]);
                slDet.SaleDetailSaleTaxPercent = 10;
                slDet.SaleDetailEatInTax = 20;
                sl.SaleDetails.Add(slDet);
                db.SaveChanges();

                if (Request["addmore"] == "Confirm and Add Another Product")
                { 
                    return View(sl);
                }
                else
                {
                    db.Entry(sl).Reference(r => r.Person).Load();
                    db.Entry(sl).Reference(r => r.Employee).Load();
                    db.Entry(sl.Employee).Reference(r => r.Person).Load();

                    return View("Receipt", sl);
                }
            }

            else
            { 
                resultMessage.MessageText = "We're so sorry, something seems to have gone wrong. Please try again.";
                return View("Result", resultMessage);
            }
        }
    }    
}

Bakery/Views/Shared/Result.cshtml
@model Bakery.Models.Message

@{
    ViewBag.Title = "Result";
}

<h2>@Html.DisplayFor(model => model.TitleText)</h2>

    @Html.DisplayFor(model => model.MessageText)

Bakery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Bob's Bakery", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Our Products", "Index", "Product")</li>
                    <li>@Html.ActionLink("New Sale", "Index", "Sale")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Lori Lynn Mahieu. Created with ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>